apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  hostPath:
    path: "/mnt/d/DevOps Road/Kubernetes/eSpace-task/hussien-task12/task2/volume"
    type: Directory
